language: python
python:
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5

install:
- pip install -r requirements.txt
- python setup.py install

script:
- echo -e 'x=0\nfor i in range(0, 10000000):\n    x+=i\nprint(x)' > fake.py
- howlong -i 1 -c python fake.py

after_success:
- bash <(curl -s https://codecov.io/bash)
